version: '3'
services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    container_name: gces_db
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    container_name: gces_app
    build: .
    volumes:
      - .:/aplicacao
    ports:
      - '3000:3000'
    depends_on:
      - db
networks:
  default:
    external:
      name: gces-network
